# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74329824d8f99c58e4cbb51c35f25c760ecd6d8e36029e80810d720939ec6ff46401173769be27344d44aca3b47eab36070453f357f219c8f23a6601a047a7f4

test:
  secret_key_base: 69060ed5c3c2d53c216ce244f670bd059a5ac29aa31d34ff76281e94f55638f1caabacb3539124c7d120db5bc73a16d214a4960a508ee427de6e280b35f20603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
